### ISSUE TITLE
Swift 3 Branch --> UIColor

### ISSUE THREAD

**Issue by exocode** [yannickl/FlowingMenu#12]
https://github.com/mediatainment/FlowingMenu/blob/swift3/Sources/FlowingMenuTransitionManager.swift#L145

remove the `()` at the end of the line...

`let shapeColor = source.colorOfElasticShapeInFlowingMenu(self) ?? menuView.backgroundColor ?? .black()`

**Comment by yannickl** [comment]
I'll update it soon. Thank you! #11
