### ISSUE TITLE
Bug when Slide left to close

### ISSUE THREAD

**Issue by Kaakati** [yannickl/FlowingMenu#5]
The View in the back becomes unresponsive when you release your finger to close before reaching 5%-10% while closing the menu.

**Comment by yannickl** [comment]
I can't reproduce the bug with my iPhone 6. On which device and iOS is it occurred? Is it occurred each time and is it some step to follow in order to produce it?

Can you provide a screenshot with the approximative distance?

Thanks

**Comment by Kaakati** [comment]
even on Simulator, but mine is iPhone 6Plus, happening when "PanToDismiss" do it multiple times, I have a Google Maps in a Container and the menu appears above the map.

**Comment by yannickl** [comment]
I've tried it multiple times without success, is it occurred with the example project? Can you record the simulator with quicktime to help me please?

_PS: sorry for the late_

**Comment by YaOfYaawi** [comment]
Heya, I have the same problem. (drag to open issue)
I'm running the app using the menu on an iPad 2 mini mainly. It is also happening on an iPhone 6.
Basically, if you drag slowly, it works fine. But from the moment you speed it up a little bit, the shape (Bezier lines) will not open completely and the app will freeze without any way to release it.

Do you have any clue where the issue could be?

I reproduced it multiple times in fact with no luck. Too bad, it is a pretty amazing animation!

**Comment by yannickl** [comment]
I think I found the issue. Just tell me if it occurs again. Thank you!
