### ISSUE TITLE
Did not call didSelectRowAtIndexPath delegate 

### ISSUE THREAD

**Issue by khushbooPS** [yannickl/FlowingMenu#9]
Hi Yannick,
Did not call didSelectRowAtIndexPath delegate in MenuController class. 
I used:

`tapGesture.cancelsTouchesInView= false`

But I did not get success. What i do? 
Please help me sir.

Khushi.

**Comment by kaich** [comment]
TapGesture prevent `didSelectRowAtIndexPath` .  I do it as below:
100th line In FlowingMenuTransitionManager 
`addTapGesture(otherView)` change to `addTapGesture(ov)` 
Hope it help you!

**Comment by antonioreyna** [comment]
Would be great to change that in the master branch :D please do. thanks!

**Comment by yannickl** [comment]
It should be fixed now!
